# fly.toml app configuration file generated for ranked-assist-server on 2024-06-10T16:47:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ranked-assist-server'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[[mounts]]
source = 'database_volume'
destination = '/mnt/volume_mount'


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
guest_path = '/mnt/volume_mount/media'
url_prefix = '/media/'

