# Generated by Django 5.0.6 on 2024-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ranked', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='votes',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='friendsgroup',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='app_ranked.profile'),
        ),
    ]
