# Generated by Django 5.0.6 on 2024-06-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ranked', '0003_remove_candidate_profile_vote_author_vote_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='rounds',
            new_name='round',
        ),
    ]
