# Generated by Django 5.0.6 on 2024-06-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ranked', '0007_candidate_votes_alter_friendsgroup_title_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='app_ranked.vote'),
            preserve_default=False,
        ),
    ]
